service: notes-app
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  iam:
    role: ${env:ROLE}
  
  httpApi:
    cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    stage:
      - dev
    httpPort: 5001

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
  createCommand:
    handler: src/command/create.handler
    events:
      - httpApi:
          path: /command
          method: post
  getCommand:
    handler: src/command/get.handler
    events:
      - httpApi:
          path: /command
          method: get
  getCommandById:
    handler: src/command/getById.handler
    events:
      - httpApi:
          path: /command/{id}
          method: get
  updateCommand:
    handler: src/command/update.handler
    events:
      - httpApi:
          path: /command/{id}
          method: put
  deleteCommand:
    handler: src/command/delete.handler
    events:
      - httpApi:
          path: /command/{id}
          method: delete
