name: Deploy to AWS S3

on :
  push:
    branches:
      - feat/infra

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel Previus Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup nodeJs
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 20.x
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Lint
        run: cd frontend && npm run lint

  build:
    needs: [avoid_reduncy, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup nodeJs
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 20.x
          cache-dependency-path: frontend/package-lock.json
      - name: Move to Frontend
        run: cd frontend
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Build App
        run: cd frontend && npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: frontend/dist

  deploy:
    needs: [build]
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: frontend/dist
      - name: Deploy to S3
        run: aws s3 sync ./dist s3://${{ secrets.BUCKET_NAME }}
